image:
  repository: tylerpitcher/webhook
  tag: 0.1.0

deployment:
  port: 80

ingress:
  enabled: true
  path: /webhook

env:
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /webhook

  - name: WEBHOOK_SIGNATURE_SECRET
    value: test
